Fix typos

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -2,9 +2,9 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 yarn test
-# yarn build
+yarn build
 
-# if [ $? -ne 0 ]; then
-#   echo "'yarn build' failed, please fix your code before pushing again"
-#   exit 1
-# fi
+if [ $? -ne 0 ]; then
+  echo "'yarn build' failed, please fix your code before pushing again"
+  exit 1
+fi
